# Generated by Django 4.2.5 on 2023-12-14 04:59

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DriverName', models.CharField(max_length=100)),
                ('DriverNumber', models.IntegerField()),
                ('CarNumber', models.CharField(max_length=15)),
                ('Experience', models.IntegerField()),
                ('Type', models.CharField(choices=[('T', 'Type 1'), ('C', 'Critical Care Transport'), ('D', 'Disaster Response'), ('S', 'Special Event Ambulance')], max_length=1)),
                ('License', models.CharField(max_length=15)),
                ('DateOfBirth', models.DateField()),
                ('Address', models.CharField(max_length=250)),
                ('Available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfBirth', models.DateField()),
                ('Address', models.CharField(max_length=250)),
                ('Contact', models.IntegerField()),
                ('BloodGroup', models.CharField(choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('O-', 'O-')], max_length=3)),
                ('Diseases', models.ManyToManyField(to='core.diseases')),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HospitalName', models.CharField(max_length=100)),
                ('CurrentDirector', models.CharField(max_length=50)),
                ('DirectorPhone', models.IntegerField()),
                ('Address', models.CharField(max_length=250)),
                ('Pincode', models.IntegerField()),
                ('YearOfOpening', models.IntegerField()),
                ('Contact', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('AmbulanceAvailable', models.BooleanField()),
                ('Multispeciality', models.BooleanField()),
                ('EmergencyOperation', models.BooleanField()),
                ('BloodBank', models.BooleanField()),
                ('ICU', models.BooleanField()),
                ('Admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Department', models.ManyToManyField(to='core.departments')),
            ],
        ),
        migrations.CreateModel(
            name='CustomSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ambulanceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ambulance')),
            ],
        ),
        migrations.CreateModel(
            name='AmbulanceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientCondition', models.CharField(choices=[('C', 'Critical/Serious'), ('W', 'Can Wait'), ('U', 'Unknown')], max_length=1)),
                ('Address', models.CharField(max_length=250)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('Injured', models.BooleanField()),
                ('CurrentStatus', models.CharField(choices=[('A', 'Accident/Severe Injuries'), ('B', 'Bleeding'), ('C', 'Childbirth/Delivery Emergencies'), ('D', 'Difficulty Breathing'), ('H', 'Heart attack/ Stroke'), ('M', 'Altered Mental State'), ('P', 'Problem in Speaking or Swallowing'), ('R', 'Severe Allergic Reaction'), ('S', 'Seizures'), ('U', 'Uncontrolled Pain'), ('F', 'UNKNOWN/found unconsious')], max_length=1)),
                ('DateTime', models.DateTimeField(default=datetime.datetime(2023, 12, 14, 10, 29, 6, 830240))),
                ('Status', models.CharField(choices=[('B', 'Booked'), ('O', 'On the Way'), ('C', 'Completed')], default='B', max_length=1)),
                ('Ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ambulance')),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ambulance',
            name='Hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital'),
        ),
    ]
